CREATE TABLE "templates" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "isPremium" BOOLEAN NOT NULL DEFAULT false,
    "primaryColor" INTEGER NOT NULL,
    "secondaryColor" INTEGER NOT NULL,
    "backgroundColor" INTEGER NOT NULL,
    "textColor" INTEGER NOT NULL,
    "subtitleColor" INTEGER NOT NULL,
    "headingFont" TEXT NOT NULL DEFAULT 'Playfair Display',
    "bodyFont" TEXT NOT NULL DEFAULT 'Poppins',
    "headingFontSize" DOUBLE PRECISION NOT NULL DEFAULT 24.0,
    "bodyFontSize" DOUBLE PRECISION NOT NULL DEFAULT 14.0,
    "photoShape" TEXT NOT NULL DEFAULT 'circle',
    "borderStyle" TEXT NOT NULL DEFAULT 'ornate',
    "sectionSpacing" DOUBLE PRECISION NOT NULL DEFAULT 16.0,
    "fieldSpacing" DOUBLE PRECISION NOT NULL DEFAULT 8.0,
    "margin" DOUBLE PRECISION NOT NULL DEFAULT 20.0,
    "headerDecoration" TEXT NOT NULL DEFAULT 'mandala',
    "footerDecoration" TEXT NOT NULL DEFAULT 'floral',
    "dividerStyle" TEXT NOT NULL DEFAULT 'minimal',
    "showWatermark" BOOLEAN NOT NULL DEFAULT false,
    "watermarkText" TEXT NOT NULL DEFAULT '',
    "sectionOrder" TEXT[] DEFAULT ARRAY['personal', 'family', 'contact']::TEXT[],
    "hiddenFields" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "labelOverrides" JSONB NOT NULL DEFAULT '{}',
    "iconStyle" TEXT NOT NULL DEFAULT 'outline',
    "backgroundImageUrl" TEXT,
    "backgroundPublicId" TEXT,
    "borderImage" TEXT NOT NULL DEFAULT '',
    "watermarkImage" TEXT NOT NULL DEFAULT '',
    "isPublished" BOOLEAN NOT NULL DEFAULT true,
    "displayOrder" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "templates_pkey" PRIMARY KEY ("id")
);
